version: "3.7"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgressql/data 
    environment:
      POSTGRES_PASSWORD: docker 
    ports:
      - "5400:5432" 

  api:
    restart: always
    build: ./api
    ports:
      - 5000:5000
    volumes: 
      - .:/api
    entrypoint: ["python3", "app.py"]

  parser:
    restart: always
    build: ./parser
    ports: 
      - 8000:8000
    # command: "gunicorn -b 0.0.0.0:8000 -k gevent wsgi:app --timeout 900"

    volumes: 
      - .:/parser
    depends_on:
      - postgres
    entrypoint: ["python3", "run.py"]
    links: 
      - postgres:postgres  

  # api:
  #   build: ./api
  #   container_name: api
  #   tty: true
  #   restart: always
  #   volumes:
  #     - api-data:/app.py
  #   ports:
  #     - "8000:8000"
  #   command: "gunicorn -b 0.0.0.0:8000 -k gevent wsgi:app --timeout 900"
  #   links:
  #     - postgres:postgres

volumes:
  db-data:
  api-data:
  parser-data: